In [1]:
import pandas as pd
import os

In [2]:
folder = "to-merge"
print(os.listdir(folder))

['A1.csv', 'A2.csv', 'A3.csv', 'A4.csv', 'A5.csv', 'expected_result.csv']

In [3]:
files_to_merge = [i for i in os.listdir(folder) if 'A' in i]

In [4]:
df_sample = pd.read_csv(os.path.join(folder, files_to_merge[4]))
df_sample

    ID  A5         Notes Dataset
0    7   1    looks good       B
1   13   1  double check       B
2    2   3      not sure       A
3    3   3  double check       B
4   14   3    looks good       B
5   15   3    looks good       B
6   18   3    looks good       B
7   16   4    looks good       A
8   17   5    looks good       A
9   22   5      not sure       B
10  12   6  double check       A
11   6   7    looks good       B
12  20   8      not sure       B
13  21   9      not sure       B
14   1  10    looks good       A
15   8  10    looks good       A
16  19  10    looks good       B

In [5]:
df_original = pd.read_csv(os.path.join(folder, files_to_merge[0]))
for i in range(len(files_to_merge[1:])):
    df = pd.read_csv(os.path.join(folder, files_to_merge[i+1]))
    df_original  = pd.merge(df_original, df, on='ID', how = 'outer')
    print(df.shape)

(18, 4)
(18, 4)
(16, 4)
(17, 4)

C:\Users\pzin\Miniconda3\envs\data-curation\lib\site-packages\ipykernel_launcher.py:4: FutureWarning: Passing 'suffixes' which cause duplicate columns {'Notes_x', 'Dataset_x'} in the result is deprecated and will raise a MergeError in a future version.
  after removing the cwd from sys.path.

In [6]:
df_original

,ID,A1,Notes_x,Dataset_x,A2,Notes_y,Dataset_y,A3,Notes_x,Dataset_x,A4,Notes_y,Dataset_y,A5,Notes,Dataset
0,20,1.0,not sure,A,5.0,not sure,A,8.0,not sure,B,4.0,not sure,B,8.0,not sure,B
1,5,2.0,looks good,A,5.0,looks good,A,10.0,looks good,B,NaN,NaN,NaN,NaN,NaN,NaN
2,6,2.0,looks good,A,3.0,looks good,A,10.0,looks good,B,10.0,looks good,B,7.0,looks good,B
3,19,2.0,looks good,A,10.0,looks good,A,2.0,looks good,B,2.0,looks good,B,10.0,looks good,B
4,1,3.0,looks good,A,1.0,looks good,A,8.0,looks good,A,5.0,looks good,A,10.0,looks good,A
5,21,3.0,not sure,A,8.0,not sure,A,NaN,NaN,NaN,NaN,NaN,NaN,9.0,not sure,B
6,17,5.0,looks good,A,3.0,looks good,A,NaN,NaN,NaN,NaN,NaN,NaN,5.0,looks good,A
7,18,5.0,looks good,B,2.0,looks good,B,NaN,NaN,NaN,NaN,NaN,NaN,3.0,looks good,B
8,8,6.0,looks good,A,9.0,looks good,A,3.0,looks good,A,10.0,looks good,A,10.0,looks good,A
9,9,6.0,looks good,A,10.0,looks good,A,1.0,looks good,A,6.0,looks good,A,NaN,NaN,NaN
10,10,6.0,looks good,B,7.0,looks good,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,2,7.0,not sure,A,3.0,not sure,A,7.0,not sure,A,3.0,not sure,A,3.0,not sure,A
12,3,7.0,double check,B,7.0,double check,B,8.0,double check,B,9.0,double check,B,3.0,double check,B
13,11,7.0,double check,A,2.0,double check,A,4.0,double check,A,8.0,double check,A,NaN,NaN,NaN
14,16,8.0,looks good,A,2.0,looks good,A,6.0,looks good,A,8.0,looks good,A,4.0,looks good,A
15,7,10.0,looks good,A,10.0,looks good,A,6.0,looks good,B,1.0,looks good,B,1.0,looks good,B
16,15,10.0,looks good,B,3.0,looks good,B,5.0,looks good,B,10.0,looks good,B,3.0,looks good,B
17,22,NaN,NaN,NaN,4.0,not sure,A,6.0,not sure,B,3.0,not sure,B,5.0,not sure,B
18,13,NaN,NaN,NaN,NaN,NaN,NaN,1.0,double check,B,5.0,double check,B,1.0,double check,B
19,14,NaN,NaN,NaN,NaN,NaN,NaN,1.0,looks good,B,2.0,looks good,B,3.0,looks good,B
20,12,NaN,NaN,NaN,NaN,NaN,NaN,6.0,double check,A,9.0,double check,A,6.0,double check,A
21,4,NaN,NaN,NaN,NaN,NaN,NaN,8.0,looks good,B,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
ID_cols  = [j for j in df_original.columns if 'ID' in j]
notes_cols = [j for j in df_original.columns if 'Notes' in j]
dataset_cols = [j for j in df_original.columns if 'Dataset' in j]

In [8]:
cols_to_address = ['Notes', 'Dataset']

df_original['Notes'] = df_original[notes_cols].apply(
    lambda x: ', '.join(x.dropna().astype(str)),
    axis=1
)

df_original['Dataset'] = df_original[dataset_cols].apply(
    lambda x: ', '.join(x.dropna().astype(str)),
    axis=1
)

In [9]:
def remove_duplicate_strings(sample):
    list_strings = sample.split(', ')
    unique_strings = list(set(list_strings))
    return ', '.join(unique_strings)

In [10]:
for i in cols_to_address:
    df_original[i] = df_original[i].apply(remove_duplicate_strings)

In [11]:
df_original

,ID,A1,Notes_x,Dataset_x,A2,Notes_y,Dataset_y,A3,Notes_x,Dataset_x,A4,Notes_y,Dataset_y,A5,Notes,Dataset
0,20,1.0,not sure,A,5.0,not sure,A,8.0,not sure,B,4.0,not sure,B,8.0,not sure,"A, B"
1,5,2.0,looks good,A,5.0,looks good,A,10.0,looks good,B,NaN,NaN,NaN,NaN,looks good,"A, B"
2,6,2.0,looks good,A,3.0,looks good,A,10.0,looks good,B,10.0,looks good,B,7.0,looks good,"A, B"
3,19,2.0,looks good,A,10.0,looks good,A,2.0,looks good,B,2.0,looks good,B,10.0,looks good,"A, B"
4,1,3.0,looks good,A,1.0,looks good,A,8.0,looks good,A,5.0,looks good,A,10.0,looks good,A
5,21,3.0,not sure,A,8.0,not sure,A,NaN,NaN,NaN,NaN,NaN,NaN,9.0,not sure,"A, B"
6,17,5.0,looks good,A,3.0,looks good,A,NaN,NaN,NaN,NaN,NaN,NaN,5.0,looks good,A
7,18,5.0,looks good,B,2.0,looks good,B,NaN,NaN,NaN,NaN,NaN,NaN,3.0,looks good,B
8,8,6.0,looks good,A,9.0,looks good,A,3.0,looks good,A,10.0,looks good,A,10.0,looks good,A
9,9,6.0,looks good,A,10.0,looks good,A,1.0,looks good,A,6.0,looks good,A,NaN,looks good,A
10,10,6.0,looks good,B,7.0,looks good,B,NaN,NaN,NaN,NaN,NaN,NaN,NaN,looks good,B
11,2,7.0,not sure,A,3.0,not sure,A,7.0,not sure,A,3.0,not sure,A,3.0,not sure,A
12,3,7.0,double check,B,7.0,double check,B,8.0,double check,B,9.0,double check,B,3.0,double check,B
13,11,7.0,double check,A,2.0,double check,A,4.0,double check,A,8.0,double check,A,NaN,double check,A
14,16,8.0,looks good,A,2.0,looks good,A,6.0,looks good,A,8.0,looks good,A,4.0,looks good,A
15,7,10.0,looks good,A,10.0,looks good,A,6.0,looks good,B,1.0,looks good,B,1.0,looks good,"A, B"
16,15,10.0,looks good,B,3.0,looks good,B,5.0,looks good,B,10.0,looks good,B,3.0,looks good,B
17,22,NaN,NaN,NaN,4.0,not sure,A,6.0,not sure,B,3.0,not sure,B,5.0,not sure,"A, B"
18,13,NaN,NaN,NaN,NaN,NaN,NaN,1.0,double check,B,5.0,double check,B,1.0,double check,B
19,14,NaN,NaN,NaN,NaN,NaN,NaN,1.0,looks good,B,2.0,looks good,B,3.0,looks good,B
20,12,NaN,NaN,NaN,NaN,NaN,NaN,6.0,double check,A,9.0,double check,A,6.0,double check,A
21,4,NaN,NaN,NaN,NaN,NaN,NaN,8.0,looks good,B,NaN,NaN,NaN,NaN,looks good,B

In [12]:
cols_to_drop = [i for i in notes_cols + dataset_cols if '_' in i]
cols_to_drop

['Notes_x',
 'Notes_y',
 'Notes_x',
 'Notes_y',
 'Dataset_x',
 'Dataset_y',
 'Dataset_x',
 'Dataset_y']

In [13]:
df_original = df_original.drop(columns=cols_to_drop)

In [14]:
df_original

    ID    A1    A2    A3    A4    A5         Notes Dataset
0   20   1.0   5.0   8.0   4.0   8.0      not sure    A, B
1    5   2.0   5.0  10.0   NaN   NaN    looks good    A, B
2    6   2.0   3.0  10.0  10.0   7.0    looks good    A, B
3   19   2.0  10.0   2.0   2.0  10.0    looks good    A, B
4    1   3.0   1.0   8.0   5.0  10.0    looks good       A
5   21   3.0   8.0   NaN   NaN   9.0      not sure    A, B
6   17   5.0   3.0   NaN   NaN   5.0    looks good       A
7   18   5.0   2.0   NaN   NaN   3.0    looks good       B
8    8   6.0   9.0   3.0  10.0  10.0    looks good       A
9    9   6.0  10.0   1.0   6.0   NaN    looks good       A
10  10   6.0   7.0   NaN   NaN   NaN    looks good       B
11   2   7.0   3.0   7.0   3.0   3.0      not sure       A
12   3   7.0   7.0   8.0   9.0   3.0  double check       B
13  11   7.0   2.0   4.0   8.0   NaN  double check       A
14  16   8.0   2.0   6.0   8.0   4.0    looks good       A
15   7  10.0  10.0   6.0   1.0   1.0    looks good    A, B
16  15  10.0   3.0   5.0  10.0   3.0    looks good       B
17  22   NaN   4.0   6.0   3.0   5.0      not sure    A, B
18  13   NaN   NaN   1.0   5.0   1.0  double check       B
19  14   NaN   NaN   1.0   2.0   3.0    looks good       B
20  12   NaN   NaN   6.0   9.0   6.0  double check       A
21   4   NaN   NaN   8.0   NaN   NaN    looks good       B

In [15]:
df_original.fillna('', inplace=True)

C:\Users\pzin\Miniconda3\envs\data-curation\lib\site-packages\pandas\core\frame.py:5177: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  downcast=downcast,

In [16]:
df_original

    ID    A1    A2    A3    A4    A5         Notes Dataset
0   20   1.0   5.0   8.0   4.0   8.0      not sure    A, B
1    5   2.0   5.0  10.0                looks good    A, B
2    6   2.0   3.0  10.0  10.0   7.0    looks good    A, B
3   19   2.0  10.0   2.0   2.0  10.0    looks good    A, B
4    1   3.0   1.0   8.0   5.0  10.0    looks good       A
5   21   3.0   8.0               9.0      not sure    A, B
6   17   5.0   3.0               5.0    looks good       A
7   18   5.0   2.0               3.0    looks good       B
8    8   6.0   9.0   3.0  10.0  10.0    looks good       A
9    9   6.0  10.0   1.0   6.0          looks good       A
10  10   6.0   7.0                      looks good       B
11   2   7.0   3.0   7.0   3.0   3.0      not sure       A
12   3   7.0   7.0   8.0   9.0   3.0  double check       B
13  11   7.0   2.0   4.0   8.0        double check       A
14  16   8.0   2.0   6.0   8.0   4.0    looks good       A
15   7  10.0  10.0   6.0   1.0   1.0    looks good    A, B
16  15  10.0   3.0   5.0  10.0   3.0    looks good       B
17  22         4.0   6.0   3.0   5.0      not sure    A, B
18  13               1.0   5.0   1.0  double check       B
19  14               1.0   2.0   3.0    looks good       B
20  12               6.0   9.0   6.0  double check       A
21   4               8.0                looks good       B

In [17]:
df_original = df_original.sort_values(by='ID', ascending=True)

In [18]:
df_original

    ID    A1    A2    A3    A4    A5         Notes Dataset
4    1   3.0   1.0   8.0   5.0  10.0    looks good       A
11   2   7.0   3.0   7.0   3.0   3.0      not sure       A
12   3   7.0   7.0   8.0   9.0   3.0  double check       B
21   4               8.0                looks good       B
1    5   2.0   5.0  10.0                looks good    A, B
2    6   2.0   3.0  10.0  10.0   7.0    looks good    A, B
15   7  10.0  10.0   6.0   1.0   1.0    looks good    A, B
8    8   6.0   9.0   3.0  10.0  10.0    looks good       A
9    9   6.0  10.0   1.0   6.0          looks good       A
10  10   6.0   7.0                      looks good       B
13  11   7.0   2.0   4.0   8.0        double check       A
20  12               6.0   9.0   6.0  double check       A
18  13               1.0   5.0   1.0  double check       B
19  14               1.0   2.0   3.0    looks good       B
16  15  10.0   3.0   5.0  10.0   3.0    looks good       B
14  16   8.0   2.0   6.0   8.0   4.0    looks good       A
6   17   5.0   3.0               5.0    looks good       A
7   18   5.0   2.0               3.0    looks good       B
3   19   2.0  10.0   2.0   2.0  10.0    looks good    A, B
0   20   1.0   5.0   8.0   4.0   8.0      not sure    A, B
5   21   3.0   8.0               9.0      not sure    A, B
17  22         4.0   6.0   3.0   5.0      not sure    A, B

In [19]:
df_original.to_csv('resulting_merged_data.csv', index=False)